
set m_dma_cfg [list \
   DMA_TYPE_SRC 0 \
   DMA_TYPE_DEST 1 \
   DMA_DATA_WIDTH_SRC 32 \
   DMA_DATA_WIDTH_DEST 32 \
   FIFO_SIZE 4 \
   DMA_LENGTH_WIDTH 32 \
]

set s_dma_cfg [list \
   DMA_TYPE_SRC  1 \
   DMA_TYPE_DEST 0 \
   DMA_DATA_WIDTH_SRC 32 \
   DMA_DATA_WIDTH_DEST 32 \
   FIFO_SIZE 4 \
   DMA_LENGTH_WIDTH 32 \
]

